### PR TITLE
Cleaned up initialization and layout.  Fixed compiler warning, added localization support.

### PR DESCRIPTION
**Pull request by rlaferla**
Fixed compiler warning for calendar identifier, added localization support, removed unused variable.

### CODE REVIEW

**Comment by matteogobbi** [comment]
Hi @rlaferla, 
I downloaded your fork, and the localized file seems to be in the folder but not in the project. Indeed, launching the project I don't see the localized string.

But anyway, if we insert the localization it should be integrated with this component, and this mean translate all the major languages and  point to a localization specific table closed in the pod.

Otherwise, please remove localization string from the pull request. 

The `layoutSubview` is ok but would be good use a specific `BOOL` variable to know if it has been built or not. It will be more clear to who read the code.

Thank you for your contribute!

**Comment by rlaferla** [comment]
Can you please add it to the project?  It is okay that it is just English because it's easy to add other languages.  I'm not going to translate it in different languages but others may.  The point is that it is now "internationalized" and ready for localization.

**Comment by matteogobbi** [comment]
Ok I try to explain better: being this a POD is a separated component that
the developer include in his project.
So If you use NSLocalizedString, it could Intercept other strings declared
from the developer with the same key.
To avoid this, exists another macro: NSLocalizedStringFromTable. This,
takes the translated strings from a particular set of translations included
in our pod. Cool. But so, being this closed, we have to provide all the
translations, otherwise the user, a part for English, will see MORNING or
DINNERTIME.

In order to release another pod version, if you don't want to complete this
thing, you can remove the localization, and submit just the layout subviews
improvement (considering a variable as explained before).

Thanks for your contribute!

On Thursday, 5 March 2015, Robert La Ferla notifications@github.com wrote:

> Can you please add it to the project? It is okay that it is just English
> because it's easy to add other languages. I'm not going to translate it in
> different languages but others may. The point is that it is now
> "internationalized" and ready for localization.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matteogobbi/MGConferenceDatePicker/pull/5#issuecomment-77284173
> .

## 

_Matteo Gobbi_
*Software iOS Engineer *

**Comment by rlaferla** [comment]
That makes sense.

**Pull request closed without merging**
